site_name: Juxta Documentation
theme:
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  name: material
  palette:
    primary: pink
    accent: pink
repo_url: https://github.com/IsmaeelAkram/juxta
repo_name: IsmaeelAkram/juxta
edit_uri: edit/docs/docs/